"""Threshold configuration for QCT classification.

Pre-T1.2, the thresholds (SS<0.20, Δ≥0.05) were chosen by inspection. In v0.3
they are derived empirically from the T1.1 ground-truth archetypes:

* ``ss_replaceable`` — 95th percentile of Surrogation Scores observed on the
  ``Regularizer`` + ``Dead Weight`` archetypes (which are known-replaceable
  by construction).
* ``intervention_load_bearing`` — 95th percentile of Δ_zero observed on the
  ``Ignored`` + ``Dead Weight`` archetypes (which are known-not-load-bearing).

The thresholds ship in ``hnep/thresholds_calibration.json`` and are
regenerated by ``scripts/recalibrate_thresholds.py``. Users with model
classes very different from the synthetic archetypes should re-derive
against their own corpus.

The legacy (0.20, 0.05) values remain importable via
:meth:`Thresholds.legacy` for backward-compatible workflows.
"""

from __future__ import annotations

import json
import warnings
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Optional, Union


_CALIBRATION_FILE = "thresholds_calibration.json"


@dataclass(frozen=True)
class Thresholds:
    """Cutoff values for binarising probe scores into QCT verdicts.

    Attributes
    ----------
    ss_replaceable
        Surrogation Score below this value classifies the quantum output as
        REPLACEABLE (a classical surrogate succeeds at mimicking it).
    intervention_load_bearing
        Relative R² drop above this value classifies the quantum component
        as LOAD-BEARING (removing it crashes the model).
    """

    ss_replaceable: float = 0.2
    intervention_load_bearing: float = 0.05

    def describe(self) -> str:
        return (
            f"Thresholds(SS<{self.ss_replaceable:.3f} ⇒ REPLACEABLE, "
            f"Δ≥{self.intervention_load_bearing:.3f} ⇒ LOAD-BEARING)"
        )

    @classmethod
    def legacy(cls) -> "Thresholds":
        """Pre-T1.2 thresholds (SS<0.20, Δ≥0.05) — kept for backward compatibility.

        These were the v0.1 / v0.2 defaults, chosen by inspection. Use them
        when comparing against published v0.1/v0.2 results.
        """
        return cls(ss_replaceable=0.20, intervention_load_bearing=0.05)

    @classmethod
    def from_calibration(
        cls, path: Optional[Union[str, Path]] = None
    ) -> "Thresholds":
        """Load thresholds from a calibration JSON.

        If ``path`` is ``None``, the package-shipped calibration is used —
        derived from the ground-truth archetypes via
        ``scripts/recalibrate_thresholds.py``. Falls back to :meth:`legacy`
        if the package data file is missing.

        Methodology
        -----------
        Thresholds are set at the **99th percentile of bootstrap-CI upper
        bounds** on the calibration archetypes — not the 99th percentile
        of point estimates. This ensures that calibration archetypes which
        should be classified as REPLACEABLE / NOT-LOAD-BEARING do not
        straddle the threshold under finite-sample bootstrap variation:
        their CIs lie strictly on the REPLACEABLE / NOT-LOAD-BEARING side
        of threshold by construction.

        The choice trades methodological softening (the SS threshold sits
        ~15% higher than a point-estimate calibration, 0.099 vs 0.0859)
        for verdict stability. Under the headline-aligned SS bootstrap
        (v0.3.0+) the point-estimate threshold flipped ~5% of REPLACEABLE
        calibration seeds to Inconclusive due to CI straddling; the
        CI-upper-bound threshold restores 100% verdict accuracy on the
        60-cell benchmark.
        """
        if path is None:
            try:
                resource = resources.files("hnep").joinpath(_CALIBRATION_FILE)
                if not resource.is_file():
                    warnings.warn(
                        "Calibration JSON not found in package data; falling "
                        "back to legacy thresholds. Run "
                        "scripts/recalibrate_thresholds.py to regenerate.",
                        RuntimeWarning,
                        stacklevel=2,
                    )
                    return cls.legacy()
                with resource.open("r") as f:
                    data = json.load(f)
            except (ModuleNotFoundError, FileNotFoundError):
                return cls.legacy()
        else:
            with open(path, "r") as f:
                data = json.load(f)
        return cls(
            ss_replaceable=float(data["ss_replaceable"]),
            intervention_load_bearing=float(data["intervention_load_bearing"]),
        )


DEFAULT_THRESHOLDS = Thresholds.from_calibration()
